/*
 * Copyright 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.example.androiddevchallenge.domain

data class Puppy(
    val id: String,
    val name: String,
    val age: String,
    val weight: String,
    val info: String,
    val breed: String,
    val energy: Int,
    val volume: Int,
    val shedding: Int
) {
    val image = "http://petharbor.com/get_image.asp?RES=Detail&ID=$id&LOCATION=DDFL"
}

val PUPPIES = listOf(
    Puppy("A0838790", "Bruce", "3 years", "63 pounds", "Bruce is a loveable, happy and a friendly guy who will light up and enhance your family life. He is strong on leash and walks best with a no pull harness. He loves to run and would make a great exercise buddy! He is playful and loves . . . loves . . . loves treats, hehe. Bruce can be sneaky, so watch out for open doors and weak backyard fences. Due to past interactions with other dogs, Bruce would be happiest as the only pet. He won’t make a great dog park dog- he’s happiest spending one on one time with you. He needs an active, experienced owner with kids over 12.", "Bull Terrier/Mix", 3, 4, 1),
    Puppy("A0839012", "Ladybug", "3 years", "48 pounds", "what a joy!, an absolute pleasure to walk, incredibly sweet and gentle. Ladybug loves treats and playing catch. She’s shy at first and warms up to nice people, but is sensitive to the touch, possibly because she has a skin issue. ", "Pit Bull", 4, 3, 1),
    Puppy("A0819772", "Ruby", "1 year", "46 pounds", "Ruby is a true gem! She’s very loving and playful. Ruby walks wonderfully on leash, and will do anything for a treat. She does well with other dogs, but would like to meet her new friend first. Ruby loves treats and knows how to sit to earn them!", "Pit Bull", 4, 3, 1),
    Puppy("A0839192", "Buddy", "4 years", "63 pounds", "Buddy is a happy, social boy who loves to stay busy. He loves going for walks, but is strong and would benefit from a no-pull harness. He appears to be house trained. He can be reactive towards other dogs while on leash and would do best not living in an apartment. Buddy needs a home with kids over 8 and as the only dog.", "Rhodesian Ridgeback", 2, 2, 1),
    Puppy("A0839956", "Guerro", "3 Years", "47 poinds", "Guero is looking for someone who is bull terrier-savy! He has many behavioral traits that are common with the breed. Guero needs to be the only dog in the home and will require lots of exercise! He tends to avoid men at first, warming up to women much faster. He has shown to have some body handling sensitivites and needs a home with kids over 14. Guero was housetrained and crate trained in his past home!", "Bull Terrier", 4, 3, 1),
    Puppy("A0840033", "Leia", "3 years", "59 pounds", "Leia came to us from a home with a large group of dogs. She has had very little socialization with new people and in new environments. She will need an experienced owner who is ok with a dog that may never be social outside of the home or with strangers. She will require extra time to adjust to a new home and may even need to work with a professional trainer. In order to set her and her new family up for success, Leia needs a quiet home without small animals (including small dogs or cats) and a fenced yard to help keep her safe while working on housetraining as she is not comfortable on leash. She will need a home with kids over 16 due to her fear level. Her first few years have been tough and with the right home, she could live a happy, long life.", "Siberian Husky", 5, 5, 4),
    Puppy("A0838073", "Lilly", "1 year", "40 pounds", "Lilly is charming and so cute! She has lots of young pup energy & loves playing with toys, running zoomies & doing all kinds of outdoor fun with you. And, she’s never met a treat she didn’t like. She may be a bit nervous when meeting some people but warms up quickly. When she’s comfortable, Lilly can get excited & jump to invite you to play with her, at the same time, she knows sit & settles. She’s very sweet & loves to be petted & rubbed. If you’re an affectionate, active person with energy to match hers, you & Lilly could be a great match! Bring the entire family to visit, kids age 14 or older. Lilly will likely do best being your only dog & the center of your attention.", "Nonspecific", 0, 0, 0),
    Puppy("A0838790", "Bruce", "3 years", "63 pounds", "Bruce is a loveable, happy and a friendly guy who will light up and enhance your family life. He is strong on leash and walks best with a no pull harness. He loves to run and would make a great exercise buddy! He is playful and loves . . . loves . . . loves treats, hehe. Bruce can be sneaky, so watch out for open doors and weak backyard fences. Due to past interactions with other dogs, Bruce would be happiest as the only pet. He won’t make a great dog park dog- he’s happiest spending one on one time with you. He needs an active, experienced owner with kids over 12.", "Bull Terrier/Mix", 3, 4, 1),
    Puppy("A0839012", "Ladybug", "3 years", "48 pounds", "what a joy!, an absolute pleasure to walk, incredibly sweet and gentle. Ladybug loves treats and playing catch. She’s shy at first and warms up to nice people, but is sensitive to the touch, possibly because she has a skin issue. ", "Pit Bull", 4, 3, 1),
    Puppy("A0819772", "Ruby", "1 year", "46 pounds", "Ruby is a true gem! She’s very loving and playful. Ruby walks wonderfully on leash, and will do anything for a treat. She does well with other dogs, but would like to meet her new friend first. Ruby loves treats and knows how to sit to earn them!", "Pit Bull", 4, 3, 1),
    Puppy("A0839192", "Buddy", "4 years", "63 pounds", "Buddy is a happy, social boy who loves to stay busy. He loves going for walks, but is strong and would benefit from a no-pull harness. He appears to be house trained. He can be reactive towards other dogs while on leash and would do best not living in an apartment. Buddy needs a home with kids over 8 and as the only dog.", "Rhodesian Ridgeback", 2, 2, 1),
    Puppy("A0839956", "Guerro", "3 Years", "47 poinds", "Guero is looking for someone who is bull terrier-savy! He has many behavioral traits that are common with the breed. Guero needs to be the only dog in the home and will require lots of exercise! He tends to avoid men at first, warming up to women much faster. He has shown to have some body handling sensitivites and needs a home with kids over 14. Guero was housetrained and crate trained in his past home!", "Bull Terrier", 4, 3, 1),
    Puppy("A0840033", "Leia", "3 years", "59 pounds", "Leia came to us from a home with a large group of dogs. She has had very little socialization with new people and in new environments. She will need an experienced owner who is ok with a dog that may never be social outside of the home or with strangers. She will require extra time to adjust to a new home and may even need to work with a professional trainer. In order to set her and her new family up for success, Leia needs a quiet home without small animals (including small dogs or cats) and a fenced yard to help keep her safe while working on housetraining as she is not comfortable on leash. She will need a home with kids over 16 due to her fear level. Her first few years have been tough and with the right home, she could live a happy, long life.", "Siberian Husky", 5, 5, 4),
    Puppy("A0838073", "Lilly", "1 year", "40 pounds", "Lilly is charming and so cute! She has lots of young pup energy & loves playing with toys, running zoomies & doing all kinds of outdoor fun with you. And, she’s never met a treat she didn’t like. She may be a bit nervous when meeting some people but warms up quickly. When she’s comfortable, Lilly can get excited & jump to invite you to play with her, at the same time, she knows sit & settles. She’s very sweet & loves to be petted & rubbed. If you’re an affectionate, active person with energy to match hers, you & Lilly could be a great match! Bring the entire family to visit, kids age 14 or older. Lilly will likely do best being your only dog & the center of your attention.", "Nonspecific", 0, 0, 0),
    Puppy("A0838790", "Bruce", "3 years", "63 pounds", "Bruce is a loveable, happy and a friendly guy who will light up and enhance your family life. He is strong on leash and walks best with a no pull harness. He loves to run and would make a great exercise buddy! He is playful and loves . . . loves . . . loves treats, hehe. Bruce can be sneaky, so watch out for open doors and weak backyard fences. Due to past interactions with other dogs, Bruce would be happiest as the only pet. He won’t make a great dog park dog- he’s happiest spending one on one time with you. He needs an active, experienced owner with kids over 12.", "Bull Terrier/Mix", 3, 4, 1),
    Puppy("A0839012", "Ladybug", "3 years", "48 pounds", "what a joy!, an absolute pleasure to walk, incredibly sweet and gentle. Ladybug loves treats and playing catch. She’s shy at first and warms up to nice people, but is sensitive to the touch, possibly because she has a skin issue. ", "Pit Bull", 4, 3, 1),
    Puppy("A0819772", "Ruby", "1 year", "46 pounds", "Ruby is a true gem! She’s very loving and playful. Ruby walks wonderfully on leash, and will do anything for a treat. She does well with other dogs, but would like to meet her new friend first. Ruby loves treats and knows how to sit to earn them!", "Pit Bull", 4, 3, 1),
    Puppy("A0839192", "Buddy", "4 years", "63 pounds", "Buddy is a happy, social boy who loves to stay busy. He loves going for walks, but is strong and would benefit from a no-pull harness. He appears to be house trained. He can be reactive towards other dogs while on leash and would do best not living in an apartment. Buddy needs a home with kids over 8 and as the only dog.", "Rhodesian Ridgeback", 2, 2, 1),
    Puppy("A0839956", "Guerro", "3 Years", "47 poinds", "Guero is looking for someone who is bull terrier-savy! He has many behavioral traits that are common with the breed. Guero needs to be the only dog in the home and will require lots of exercise! He tends to avoid men at first, warming up to women much faster. He has shown to have some body handling sensitivites and needs a home with kids over 14. Guero was housetrained and crate trained in his past home!", "Bull Terrier", 4, 3, 1),
    Puppy("A0840033", "Leia", "3 years", "59 pounds", "Leia came to us from a home with a large group of dogs. She has had very little socialization with new people and in new environments. She will need an experienced owner who is ok with a dog that may never be social outside of the home or with strangers. She will require extra time to adjust to a new home and may even need to work with a professional trainer. In order to set her and her new family up for success, Leia needs a quiet home without small animals (including small dogs or cats) and a fenced yard to help keep her safe while working on housetraining as she is not comfortable on leash. She will need a home with kids over 16 due to her fear level. Her first few years have been tough and with the right home, she could live a happy, long life.", "Siberian Husky", 5, 5, 4),
    Puppy("A0838073", "Lilly", "1 year", "40 pounds", "Lilly is charming and so cute! She has lots of young pup energy & loves playing with toys, running zoomies & doing all kinds of outdoor fun with you. And, she’s never met a treat she didn’t like. She may be a bit nervous when meeting some people but warms up quickly. When she’s comfortable, Lilly can get excited & jump to invite you to play with her, at the same time, she knows sit & settles. She’s very sweet & loves to be petted & rubbed. If you’re an affectionate, active person with energy to match hers, you & Lilly could be a great match! Bring the entire family to visit, kids age 14 or older. Lilly will likely do best being your only dog & the center of your attention.", "Nonspecific", 0, 0, 0)
)
